<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<!-- 2022-10-27 Thu 06:45 -->
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Programming Android with Kotlin Achieving Structured Concurrency with Coroutines</title>
<meta name="generator" content="Org Mode" />
<link rel="stylesheet" href="static/x.css" type="text/css"/><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div id="content" class="content">
<h1 class="title">Programming Android with Kotlin Achieving Structured Concurrency with Coroutines</h1>
<div id="table-of-contents" role="doc-toc">
<h2>Table of Contents</h2>
<div id="text-table-of-contents" role="doc-toc">
<ul>
<li><a href="#orge3e71a2">1. Coroutine</a></li>
<li><a href="#org27f5155">2. Channel</a>
<ul>
<li><a href="#org7b822da">2.1. What is a <code>Channel</code>?</a></li>
<li><a href="#orgaf613df">2.2. How to use a <code>Channel</code> without buffer?</a></li>
<li><a href="#org4bd37e9">2.3. Which <code>Channel</code> flavors does coroutine provide?</a></li>
</ul>
</li>
<li><a href="#org8c45b4e">3. Flow</a>
<ul>
<li><a href="#org4edaf20">3.1. How to make a flow from callbacked api?</a></li>
<li><a href="#orgb2ba753">3.2. How to transform a stream of values concurrently?</a></li>
<li><a href="#org7ebf9b6">3.3. How to implement a <code>bufferTimeout</code> operator?</a></li>
<li><a href="#orgc9502dc">3.4. A <code>try/catch</code> statement inside a flow builder might catch <i>downstream</i> exceptions &#x2013; which includes exceptions raised during the collection of the flow.</a></li>
<li><a href="#org556a113">3.5. When to use <code>try/catch</code> with the flow?</a></li>
<li><a href="#org56db1c5">3.6. How to handle exceptions inside the flow?</a></li>
<li><a href="#org0fe069b">3.7. How to build a flow with exceptions?</a></li>
<li><a href="#org6466e21">3.8. How to implement a <code>mapWithRetry</code> operator?</a></li>
</ul>
</li>
</ul>
</div>
</div>
<dl class="org-dl">
<dt>start</dt><dd><span class="timestamp-wrapper"><span class="timestamp">&lt;2022-09-15 Thu 09:26&gt;</span></span></dd>
</dl>


<div id="outline-container-orge3e71a2" class="outline-2">
<h2 id="orge3e71a2"><span class="section-number-2">1.</span> Coroutine</h2>
<div class="outline-text-2" id="text-1">
<p>
Conceptually, a <code>job</code> is a cancellable thing with a life-cycle that culminates in its completion.
</p>

<p>
<code>async</code> returns a <code>Deferred</code> instance, which is a specialized <code>Job</code> with a return value.
</p>

<p>
A <code>CoroutineScope</code> is an object that plays the role of the parent in structured concurrency&#x2013;its purpose is to manage and monitor the coroutines you create inside it.
</p>

<div class="org-src-container">
<pre class="src src-kotlin">interface CoroutineScope {
  val coroutineContext: CoroutineContext
}
</pre>
</div>

<p>
In other words, a <code>CoroutineScope</code> is a container for a <code>CoroutineContext</code>.
</p>

<p>
In practice, you'll most often use a special context element to control which thread, or which thread poll, will execute your coroutine(s).
</p>

<p>
Cancellation: designed or failure
</p>

<p>
Make callback suspendable with <code>suspendCancellableCoroutine</code>:
</p>
<div class="org-src-container">
<pre class="src src-kotlin">suspend fun Call.await() = suspendCancellableCoroutine&lt;ResponseBody?&gt; { continuation -&gt;
  continuation.invokeOnCancellation {
    cancel()
  }

  enqueue(object: Callback {
    override fun onResponse(call: Call, response: Response) {
      continuation.resume(response.body())
    }

    override fun onFailure(call: Call, e: IOException) {
      continuation.resumeWithException(e)
    }
  })
}
</pre>
</div>

<p>
Catch the unhandled coroutine exceptions with <code>CoroutineExceptionHandler</code>:
</p>
<div class="org-src-container">
<pre class="src src-kotlin">fun main() = runBlocking {
  val ceh = CoroutineExceptionHandler { _, exception -&gt;
    println("Caught $exception with suppressed ${exception.suppressed.contentToString()}")
  }
  val scope = CoroutineScope(coroutineContext + ceh + Job())

  val job = scope.launch {
    try {
      throw AssertionError()
    } finally {
      withContext(NonCancellable) {
        println("Throwing exception from finally")
        throw ArithmeticException() // This exception is added to the `suppressed` list of the previous exception.
      }
    }
  }
  job.join()
}
</pre>
</div>

<p>
Stop exceptions' propagation with <code>SupervisorJob</code>:
</p>
<div class="org-src-container">
<pre class="src src-kotlin">fun main() = runBlocking {
  val ceh = CoroutineExceptionHandler { _, exception -&gt;
    println("Caught $exception with suppressed ${exception.suppressed.contentToString()}")
  }
  val supervisor = SupervisorJob()
  val scope = CoroutineScope(coroutineContext + supervisor)
  with(scope) {
    // upon could be replaced with supervisorScope
    val firstChild = launch(ceh) {
      println("First child is failing")
      throw AssertionError("First child is cancelled")
    }

    val secondChild = launch {
      firstChild.join()

      delay(10)
      println("First child is cancelled: ${firstChild.isCancelled}, but second one is still active")
    }

    // wait until the second child completes
    secondChild.join()
  }
}
</pre>
</div>

<p>
<code>withContext</code> could be replaced with <code>coroutineScope</code>
</p>

<p>
Use <code>runCatching</code> instead of <code>try/catch</code>:
</p>
<div class="org-src-container">
<pre class="src src-kotlin">scope.launch {
  val result = runCatching {
    regularFunctionWhichCanThrowException()
  }

  if (result.isSuccess) {
    // no exception was thrown
  } else {
    // exception was thrown
  }
}
</pre>
</div>

<ul class="org-ul">
<li>If the failure of a child should also cancel other children, use a regular scope. Otherwise, use a supervisor scope.</li>
<li><code>async</code> exposes exceptions, which can be caught by wrapping the <code>await</code> call in a <code>try/catch</code>. On the other hand, <code>launch</code> treats uncaught exceptions as unhandled, which can be handled using a CEH.</li>
</ul>

<p>
Unknown concepts or API:
</p>
<ul class="org-ul">
<li><code>Job.join()</code>: wait the job complete</li>
<li><code>yield</code>: give a chance to suspend unsuspendable block</li>
</ul>
</div>
</div>


<div id="outline-container-org27f5155" class="outline-2">
<h2 id="org27f5155"><span class="section-number-2">2.</span> Channel</h2>
<div class="outline-text-2" id="text-2">
</div>
<div id="outline-container-org7b822da" class="outline-3">
<h3 id="org7b822da"><span class="section-number-3">2.1.</span> What is a <code>Channel</code>?</h3>
<div class="outline-text-3" id="text-2-1">
<p>
A <code>Channel</code> can be see just like that: a queue with suspending functions <code>send</code> and <code>receive</code>.
</p>
</div>
</div>
<div id="outline-container-orgaf613df" class="outline-3">
<h3 id="orgaf613df"><span class="section-number-3">2.2.</span> How to use a <code>Channel</code> without buffer?</h3>
<div class="outline-text-3" id="text-2-2">
<div class="org-src-container">
<pre class="src src-kotlin">fun main() = runBlocking {
  val channel = Channel&lt;Int&gt;()
  launch {
    for (x in 1..5) channel.send(x * x)
    channel.close()
  }

  for (y in channel) println(y)
}
</pre>
</div>
</div>
</div>
<div id="outline-container-org4bd37e9" class="outline-3">
<h3 id="org4bd37e9"><span class="section-number-3">2.3.</span> Which <code>Channel</code> flavors does coroutine provide?</h3>
<div class="outline-text-3" id="text-2-3">
<ol class="org-ol">
<li>RENDEZVOUS: 0</li>
<li>UNLIMITED</li>
<li>CONFLATED: 1, just recevie the last value</li>
<li>BUFFERED: when over capacity, receive start</li>
</ol>
</div>
</div>
</div>
<div id="outline-container-org8c45b4e" class="outline-2">
<h2 id="org8c45b4e"><span class="section-number-2">3.</span> Flow</h2>
<div class="outline-text-2" id="text-3">
</div>
<div id="outline-container-org4edaf20" class="outline-3">
<h3 id="org4edaf20"><span class="section-number-3">3.1.</span> How to make a flow from callbacked api?</h3>
<div class="outline-text-3" id="text-3-1">
<div class="org-src-container">
<pre class="src src-kotlin">fun messageFlow() = callbackFlow&lt;Message&gt; {
  // 1. Instantiate the "callback." In this case, it's an observer.
  val cb = object : Callback {
    override fun onMessage(message: Message) {
      trySend(message)
    }

    override fun onClosed() {
      channel.close()
    }

    override fun onFailure(t: Throwable) {
      cancel(CancellationException("Failure", t))
    }
  }
  // 2. Register that callback using the available api.
  addCallback(cb)
  // 3. Listen for close event using `awaitClose`, and provide a relevant action
  // to take in this case. Most probably, you'll have to unregister the callback.
  awaitClose { removeCallback(cb) }
}
</pre>
</div>
</div>
</div>
<div id="outline-container-orgb2ba753" class="outline-3">
<h3 id="orgb2ba753"><span class="section-number-3">3.2.</span> How to transform a stream of values concurrently?</h3>
<div class="outline-text-3" id="text-3-2">
<div class="org-src-container">
<pre class="src src-kotlin">suspend fun transform(loc: Location): Content = withContext(Dispatchers.IO) {
  // do some work
}

fun main() = runBlocking {
  val contentFlow = locationsFlow.map {
    flow {
      emit(transform(it))
    }
  }.flattenMerge(4)

  val contents = contentFlow.toList()
}
</pre>
</div>
</div>
</div>
<div id="outline-container-org7ebf9b6" class="outline-3">
<h3 id="org7ebf9b6"><span class="section-number-3">3.3.</span> How to implement a <code>bufferTimeout</code> operator?</h3>
<div class="outline-text-3" id="text-3-3">
<div class="org-src-container">
<pre class="src src-kotlin">fun &lt;T&gt; Flow&lt;T&gt;.bufferTimeout(timeoutMillis: Long, capacity: Int = 16): Flow&lt;List&lt;T&gt;&gt; = flow {
  require(capacity &gt; 0) { "Buffer capacity must be positive" }
  require(timeoutMillis &gt; 0) { "Timeout must be positive" }

  coroutineScope {
    // Consume the upstram flow and send them over a channel.
    val channel = produceIn(this)
    val buffer = mutableListOf&lt;T&gt;()
    val ticker = ticker(timeoutMillis)

    suspend fun flush() {
      if (buffer.isNotEmpty()) {
        emit(buffer.toList())
        buffer.clear()
      }
    }

    try {
      whileSelect {
        channel.onReceive {
          buffer.add(it)
          if (buffer.size == capacity) {
            flush()
          }
          true
        }
        ticker.onReceive {
          flush()
          true
        }
      } catch (e: ClosedReceiveChannelException) {
        // When  the  upstream  flow  collection  completes,  the  coroutine  started  with `produceIn`
        // will still attempt to read from that flow, and a `ClosedReceiveChannelException`  will
         // be  raised.  So  we  catch  that  exception, and we know that we should flush the content
        // of the buffer.
        flush()
      } finnaly {
        channel.cancel()
        ticker.cancel()
      }
    }
  }
}

suspend fun main() {
  val flow = (1..100).asFlow().onEach { delay(10) }
  val startTime = System.currentTimeMillis()
  flow.bufferTimeout(50, 10).collect {
    println("${System.currentTimeMillis() - startTime} ms: $it")
  }
}
</pre>
</div>
</div>
</div>
<div id="outline-container-orgc9502dc" class="outline-3">
<h3 id="orgc9502dc"><span class="section-number-3">3.4.</span> A <code>try/catch</code> statement inside a flow builder might catch <i>downstream</i> exceptions &#x2013; which includes exceptions raised during the collection of the flow.</h3>
</div>
<div id="outline-container-org556a113" class="outline-3">
<h3 id="org556a113"><span class="section-number-3">3.5.</span> When to use <code>try/catch</code> with the flow?</h3>
<div class="outline-text-3" id="text-3-5">
<p>
The <code>try/catch</code> block should <i>only</i> be used to surround the collector, to handle exceptions raised from the collector itself, or (possibly, although it’s not ideal) to handle exceptions raised from the flow.
</p>

<div class="org-src-container">
<pre class="src src-kotlin">try {
  aFlow.collect {
    // ...
  }
} catch (e: Exception) {
  // ...
}
</pre>
</div>
</div>
</div>
<div id="outline-container-org56db1c5" class="outline-3">
<h3 id="org56db1c5"><span class="section-number-3">3.6.</span> How to handle exceptions inside the flow?</h3>
<div class="outline-text-3" id="text-3-6">
<p>
Use <code>catch</code> operator.
</p>
</div>
</div>
<div id="outline-container-org0fe069b" class="outline-3">
<h3 id="org0fe069b"><span class="section-number-3">3.7.</span> How to build a flow with exceptions?</h3>
<div class="outline-text-3" id="text-3-7">
<div class="org-src-container">
<pre class="src src-kotlin">data class Image(val url: String)

sealed calss Result
data class Success(val image: Image) : Result()
data class Error(val url: String) : Result()

suspend fun fetchImage(url: String): Image {
  // simulate network request
  delay(10)

  // simulate an exception thrown by the network request
  if (url.contains("error")) {
    throw IOException("Network error")
  }

  return Image(url)
}

suspend fun fetchImageWithResult(url: String): Result {
  println("fetchImageWithResult: $url")
  return try {
    Success(fetchImage(url))
  } catch (e: IOException) {
    Error(url)
  }
}

fun main() = runBlocking {
  val urls = flowOf(
    "https://www.google.com",
    "https://www.google.com/error",
    "https://www.google.com"
  )

  urls.map { url -&gt;
    fetchImageWithResult(url)
  }.collect {
    println("Result: $it")
  }
}
</pre>
</div>
</div>
</div>
<div id="outline-container-org6466e21" class="outline-3">
<h3 id="org6466e21"><span class="section-number-3">3.8.</span> How to implement a <code>mapWithRetry</code> operator?</h3>
<div class="outline-text-3" id="text-3-8">
<div class="org-src-container">
<pre class="src src-kotlin">fun &lt;T, R: Any&gt; Flow&lt;T&gt;.mapWithRetry(
  action: suspend (T) -&gt; R,
  predicate: suspend (R, attempt: Int) -&gt; Boolean
) = map { data -&gt;
  var attempt = 0
  var shallRetry: Boolean
  var lastValue: R? = null

  do {
    val tr = action(data)
    shallRetry = predicate(tr, ++attempt)
    if (!shallRetry) {
      lastValue = tr
    }
  } while (shallRetry)
  return@map lastValue
}

fun main = runBlocking {
  val flow = flowOf(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
  flow.mapWithRetry(
    action = { value -&gt;
      println("action: $value")
      value
    },
    predicate = { value, attempt -&gt;
      value % 2 == 0 &amp;&amp; attempt &lt; 3
    }
  ).collect {
    println("collect: $it")
  }
}
</pre>
</div>
<p>
Hot Flows with SharedFlow
</p>
</div>
</div>
</div>
</div>
<div id="postamble" class="status">
<div class="links"><a href="#content">T</a><a href="index.html">H</a><a id="share-img">I</a><a href="20210629191000-000_index.html">0</a></div><script src="static/dom2img.min.js" type="text/javascript"></script><script src="static/x.js" type="text/javascript"></script>
</div>
</body>
</html>
