<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<!-- 2022-11-11 Fri 17:13 -->
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Programming Android with Kotlin Achieving Structured Concurrency with Coroutines</title>
<meta name="generator" content="Org Mode" />
<link rel="stylesheet" href="static/x.css" type="text/css"/><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div id="content" class="content">
<h1 class="title">Programming Android with Kotlin Achieving Structured Concurrency with Coroutines</h1>
<div id="table-of-contents" role="doc-toc">
<h2>Table of Contents</h2>
<div id="text-table-of-contents" role="doc-toc">
<ul>
<li><a href="#orgea0a4ed">1. Coroutine</a></li>
<li><a href="#orgf6c4f15">2. Channel</a>
<ul>
<li><a href="#org6f8712e">2.1. What is a <code>Channel</code>?</a></li>
<li><a href="#org7cd3dfc">2.2. How to use a <code>Channel</code> without buffer?</a></li>
<li><a href="#org8ef31c8">2.3. Which <code>Channel</code> flavors does coroutine provide?</a></li>
</ul>
</li>
<li><a href="#org20d6f66">3. Flow</a>
<ul>
<li><a href="#org0083d84">3.1. How to make a flow from callbacked api?</a></li>
<li><a href="#org2f92a7c">3.2. How to transform a stream of values concurrently?</a></li>
<li><a href="#orgcbc4fa5">3.3. How to implement a <code>bufferTimeout</code> operator?</a></li>
<li><a href="#org7e76336">3.4. A <code>try/catch</code> statement inside a flow builder might catch <i>downstream</i> exceptions &#x2013; which includes exceptions raised during the collection of the flow.</a></li>
<li><a href="#org58d4e84">3.5. When to use <code>try/catch</code> with the flow?</a></li>
<li><a href="#org28db35e">3.6. How to handle exceptions inside the flow?</a></li>
<li><a href="#orgbb0c1a1">3.7. How to build a flow with exceptions?</a></li>
<li><a href="#orgcf6e105">3.8. How to implement a <code>mapWithRetry</code> operator?</a></li>
<li><a href="#orgbc69172">3.9. How to share emitted values among several collectors?</a></li>
<li><a href="#orgddd8cfe">3.10. Why are there two methods to emit values exposed by <code>MutableSharedFlow</code>?</a></li>
<li><a href="#org9578664">3.11. How to <code>replay</code> values for new collectors?</a></li>
</ul>
</li>
</ul>
</div>
</div>
<dl class="org-dl">
<dt>start</dt><dd><span class="timestamp-wrapper"><span class="timestamp">&lt;2022-09-15 Thu 09:26&gt;</span></span></dd>
</dl>


<div id="outline-container-orgea0a4ed" class="outline-2">
<h2 id="orgea0a4ed"><span class="section-number-2">1.</span> Coroutine</h2>
<div class="outline-text-2" id="text-1">
<p>
Conceptually, a <code>job</code> is a cancellable thing with a life-cycle that culminates in its completion.
</p>

<p>
<code>async</code> returns a <code>Deferred</code> instance, which is a specialized <code>Job</code> with a return value.
</p>

<p>
A <code>CoroutineScope</code> is an object that plays the role of the parent in structured concurrency&#x2013;its purpose is to manage and monitor the coroutines you create inside it.
</p>

<div class="org-src-container">
<pre class="src src-kotlin">interface CoroutineScope {
  val coroutineContext: CoroutineContext
}
</pre>
</div>

<p>
In other words, a <code>CoroutineScope</code> is a container for a <code>CoroutineContext</code>.
</p>

<p>
In practice, you'll most often use a special context element to control which thread, or which thread poll, will execute your coroutine(s).
</p>

<p>
Cancellation: designed or failure
</p>

<p>
Make callback suspendable with <code>suspendCancellableCoroutine</code>:
</p>
<div class="org-src-container">
<pre class="src src-kotlin">suspend fun Call.await() = suspendCancellableCoroutine&lt;ResponseBody?&gt; { continuation -&gt;
  continuation.invokeOnCancellation {
    cancel()
  }

  enqueue(object: Callback {
    override fun onResponse(call: Call, response: Response) {
      continuation.resume(response.body())
    }

    override fun onFailure(call: Call, e: IOException) {
      continuation.resumeWithException(e)
    }
  })
}
</pre>
</div>

<p>
Catch the unhandled coroutine exceptions with <code>CoroutineExceptionHandler</code>:
</p>
<div class="org-src-container">
<pre class="src src-kotlin">fun main() = runBlocking {
  val ceh = CoroutineExceptionHandler { _, exception -&gt;
    println("Caught $exception with suppressed ${exception.suppressed.contentToString()}")
  }
  val scope = CoroutineScope(coroutineContext + ceh + Job())

  val job = scope.launch {
    try {
      throw AssertionError()
    } finally {
      withContext(NonCancellable) {
        println("Throwing exception from finally")
        throw ArithmeticException() // This exception is added to the `suppressed` list of the previous exception.
      }
    }
  }
  job.join()
}
</pre>
</div>

<p>
Stop exceptions' propagation with <code>SupervisorJob</code>:
</p>
<div class="org-src-container">
<pre class="src src-kotlin">fun main() = runBlocking {
  val ceh = CoroutineExceptionHandler { _, exception -&gt;
    println("Caught $exception with suppressed ${exception.suppressed.contentToString()}")
  }
  val supervisor = SupervisorJob()
  val scope = CoroutineScope(coroutineContext + supervisor)
  with(scope) {
    // upon could be replaced with supervisorScope
    val firstChild = launch(ceh) {
      println("First child is failing")
      throw AssertionError("First child is cancelled")
    }

    val secondChild = launch {
      firstChild.join()

      delay(10)
      println("First child is cancelled: ${firstChild.isCancelled}, but second one is still active")
    }

    // wait until the second child completes
    secondChild.join()
  }
}
</pre>
</div>

<p>
<code>withContext</code> could be replaced with <code>coroutineScope</code>
</p>

<p>
Use <code>runCatching</code> instead of <code>try/catch</code>:
</p>
<div class="org-src-container">
<pre class="src src-kotlin">scope.launch {
  val result = runCatching {
    regularFunctionWhichCanThrowException()
  }

  if (result.isSuccess) {
    // no exception was thrown
  } else {
    // exception was thrown
  }
}
</pre>
</div>

<ul class="org-ul">
<li>If the failure of a child should also cancel other children, use a regular scope. Otherwise, use a supervisor scope.</li>
<li><code>async</code> exposes exceptions, which can be caught by wrapping the <code>await</code> call in a <code>try/catch</code>. On the other hand, <code>launch</code> treats uncaught exceptions as unhandled, which can be handled using a CEH.</li>
</ul>

<p>
Unknown concepts or API:
</p>
<ul class="org-ul">
<li><code>Job.join()</code>: wait the job complete</li>
<li><code>yield</code>: give a chance to suspend unsuspendable block</li>
</ul>
</div>
</div>


<div id="outline-container-orgf6c4f15" class="outline-2">
<h2 id="orgf6c4f15"><span class="section-number-2">2.</span> Channel</h2>
<div class="outline-text-2" id="text-2">
</div>
<div id="outline-container-org6f8712e" class="outline-3">
<h3 id="org6f8712e"><span class="section-number-3">2.1.</span> What is a <code>Channel</code>?</h3>
<div class="outline-text-3" id="text-2-1">
<p>
A <code>Channel</code> can be see just like that: a queue with suspending functions <code>send</code> and <code>receive</code>.
</p>
</div>
</div>
<div id="outline-container-org7cd3dfc" class="outline-3">
<h3 id="org7cd3dfc"><span class="section-number-3">2.2.</span> How to use a <code>Channel</code> without buffer?</h3>
<div class="outline-text-3" id="text-2-2">
<div class="org-src-container">
<pre class="src src-kotlin">fun main() = runBlocking {
  val channel = Channel&lt;Int&gt;()
  launch {
    for (x in 1..5) channel.send(x * x)
    channel.close()
  }

  for (y in channel) println(y)
}
</pre>
</div>
</div>
</div>
<div id="outline-container-org8ef31c8" class="outline-3">
<h3 id="org8ef31c8"><span class="section-number-3">2.3.</span> Which <code>Channel</code> flavors does coroutine provide?</h3>
<div class="outline-text-3" id="text-2-3">
<ol class="org-ol">
<li>RENDEZVOUS: 0</li>
<li>UNLIMITED</li>
<li>CONFLATED: 1, just recevie the last value</li>
<li>BUFFERED: when over capacity, receive start</li>
</ol>
</div>
</div>
</div>
<div id="outline-container-org20d6f66" class="outline-2">
<h2 id="org20d6f66"><span class="section-number-2">3.</span> Flow</h2>
<div class="outline-text-2" id="text-3">
</div>
<div id="outline-container-org0083d84" class="outline-3">
<h3 id="org0083d84"><span class="section-number-3">3.1.</span> How to make a flow from callbacked api?</h3>
<div class="outline-text-3" id="text-3-1">
<div class="org-src-container">
<pre class="src src-kotlin">fun messageFlow() = callbackFlow&lt;Message&gt; {
  // 1. Instantiate the "callback." In this case, it's an observer.
  val cb = object : Callback {
    override fun onMessage(message: Message) {
      trySend(message)
    }

    override fun onClosed() {
      channel.close()
    }

    override fun onFailure(t: Throwable) {
      cancel(CancellationException("Failure", t))
    }
  }
  // 2. Register that callback using the available api.
  addCallback(cb)
  // 3. Listen for close event using `awaitClose`, and provide a relevant action
  // to take in this case. Most probably, you'll have to unregister the callback.
  awaitClose { removeCallback(cb) }
}
</pre>
</div>
</div>
</div>
<div id="outline-container-org2f92a7c" class="outline-3">
<h3 id="org2f92a7c"><span class="section-number-3">3.2.</span> How to transform a stream of values concurrently?</h3>
<div class="outline-text-3" id="text-3-2">
<div class="org-src-container">
<pre class="src src-kotlin">suspend fun transform(loc: Location): Content = withContext(Dispatchers.IO) {
  // do some work
}

fun main() = runBlocking {
  val contentFlow = locationsFlow.map {
    flow {
      emit(transform(it))
    }
  }.flattenMerge(4)

  val contents = contentFlow.toList()
}
</pre>
</div>
</div>
</div>
<div id="outline-container-orgcbc4fa5" class="outline-3">
<h3 id="orgcbc4fa5"><span class="section-number-3">3.3.</span> How to implement a <code>bufferTimeout</code> operator?</h3>
<div class="outline-text-3" id="text-3-3">
<div class="org-src-container">
<pre class="src src-kotlin">fun &lt;T&gt; Flow&lt;T&gt;.bufferTimeout(timeoutMillis: Long, capacity: Int = 16): Flow&lt;List&lt;T&gt;&gt; = flow {
  require(capacity &gt; 0) { "Buffer capacity must be positive" }
  require(timeoutMillis &gt; 0) { "Timeout must be positive" }

  coroutineScope {
    // Consume the upstram flow and send them over a channel.
    val channel = produceIn(this)
    val buffer = mutableListOf&lt;T&gt;()
    val ticker = ticker(timeoutMillis)

    suspend fun flush() {
      if (buffer.isNotEmpty()) {
        emit(buffer.toList())
        buffer.clear()
      }
    }

    try {
      whileSelect {
        channel.onReceive {
          buffer.add(it)
          if (buffer.size == capacity) {
            flush()
          }
          true
        }
        ticker.onReceive {
          flush()
          true
        }
      } catch (e: ClosedReceiveChannelException) {
        // When  the  upstream  flow  collection  completes,  the  coroutine  started  with `produceIn`
        // will still attempt to read from that flow, and a `ClosedReceiveChannelException`  will
         // be  raised.  So  we  catch  that  exception, and we know that we should flush the content
        // of the buffer.
        flush()
      } finnaly {
        channel.cancel()
        ticker.cancel()
      }
    }
  }
}

suspend fun main() {
  val flow = (1..100).asFlow().onEach { delay(10) }
  val startTime = System.currentTimeMillis()
  flow.bufferTimeout(50, 10).collect {
    println("${System.currentTimeMillis() - startTime} ms: $it")
  }
}
</pre>
</div>
</div>
</div>
<div id="outline-container-org7e76336" class="outline-3">
<h3 id="org7e76336"><span class="section-number-3">3.4.</span> A <code>try/catch</code> statement inside a flow builder might catch <i>downstream</i> exceptions &#x2013; which includes exceptions raised during the collection of the flow.</h3>
</div>
<div id="outline-container-org58d4e84" class="outline-3">
<h3 id="org58d4e84"><span class="section-number-3">3.5.</span> When to use <code>try/catch</code> with the flow?</h3>
<div class="outline-text-3" id="text-3-5">
<p>
The <code>try/catch</code> block should <i>only</i> be used to surround the collector, to handle exceptions raised from the collector itself, or (possibly, although it’s not ideal) to handle exceptions raised from the flow.
</p>

<div class="org-src-container">
<pre class="src src-kotlin">try {
  aFlow.collect {
    // ...
  }
} catch (e: Exception) {
  // ...
}
</pre>
</div>
</div>
</div>
<div id="outline-container-org28db35e" class="outline-3">
<h3 id="org28db35e"><span class="section-number-3">3.6.</span> How to handle exceptions inside the flow?</h3>
<div class="outline-text-3" id="text-3-6">
<p>
Use <code>catch</code> operator.
</p>
</div>
</div>
<div id="outline-container-orgbb0c1a1" class="outline-3">
<h3 id="orgbb0c1a1"><span class="section-number-3">3.7.</span> How to build a flow with exceptions?</h3>
<div class="outline-text-3" id="text-3-7">
<div class="org-src-container">
<pre class="src src-kotlin">data class Image(val url: String)

sealed calss Result
data class Success(val image: Image) : Result()
data class Error(val url: String) : Result()

suspend fun fetchImage(url: String): Image {
  // simulate network request
  delay(10)

  // simulate an exception thrown by the network request
  if (url.contains("error")) {
    throw IOException("Network error")
  }

  return Image(url)
}

suspend fun fetchImageWithResult(url: String): Result {
  println("fetchImageWithResult: $url")
  return try {
    Success(fetchImage(url))
  } catch (e: IOException) {
    Error(url)
  }
}

fun main() = runBlocking {
  val urls = flowOf(
    "https://www.google.com",
    "https://www.google.com/error",
    "https://www.google.com"
  )

  urls.map { url -&gt;
    fetchImageWithResult(url)
  }.collect {
    println("Result: $it")
  }
}
</pre>
</div>
</div>
</div>
<div id="outline-container-orgcf6e105" class="outline-3">
<h3 id="orgcf6e105"><span class="section-number-3">3.8.</span> How to implement a <code>mapWithRetry</code> operator?</h3>
<div class="outline-text-3" id="text-3-8">
<div class="org-src-container">
<pre class="src src-kotlin">fun &lt;T, R: Any&gt; Flow&lt;T&gt;.mapWithRetry(
  action: suspend (T) -&gt; R,
  predicate: suspend (R, attempt: Int) -&gt; Boolean
) = map { data -&gt;
  var attempt = 0
  var shallRetry: Boolean
  var lastValue: R? = null

  do {
    val tr = action(data)
    shallRetry = predicate(tr, ++attempt)
    if (!shallRetry) {
      lastValue = tr
    }
  } while (shallRetry)
  return@map lastValue
}

fun main = runBlocking {
  val flow = flowOf(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
  flow.mapWithRetry(
    action = { value -&gt;
      println("action: $value")
      value
    },
    predicate = { value, attempt -&gt;
      value % 2 == 0 &amp;&amp; attempt &lt; 3
    }
  ).collect {
    println("collect: $it")
  }
}
</pre>
</div>
</div>
</div>

<div id="outline-container-orgbc69172" class="outline-3">
<h3 id="orgbc69172"><span class="section-number-3">3.9.</span> How to share emitted values among several collectors?</h3>
<div class="outline-text-3" id="text-3-9">
<p>
<code>SharedFlow</code>
</p>
</div>
</div>
<div id="outline-container-orgddd8cfe" class="outline-3">
<h3 id="orgddd8cfe"><span class="section-number-3">3.10.</span> Why are there two methods to emit values exposed by <code>MutableSharedFlow</code>?</h3>
<div class="outline-text-3" id="text-3-10">
<p>
默认情况下，当 <code>MutableSharedFlow</code> 使用 <code>emit</code> 发射一个值时，它会暂停直到所有订阅者开始处理这个值。
</p>

<p>
然而，有时这并不是你想做的。你会发现你必须从非暂停的代码中发射值的情况。因此，出现<code>了tryEmit</code>，它试图立即发射一个值，如果成功则返回真，否则返回假。
</p>
</div>
</div>
<div id="outline-container-org9578664" class="outline-3">
<h3 id="org9578664"><span class="section-number-3">3.11.</span> How to <code>replay</code> values for new collectors?</h3>
<div class="outline-text-3" id="text-3-11">
<p>
一个 <code>replay &gt; 0</code> 的共享流在内部使用一个缓存，其工作方式与通道类似。例如，如果你创建了一个 <code>replay = 3</code> 的共享流，前三个 <code>emit</code> 调用就不会暂停。在这种情况下，<code>emit</code> 和 <code>tryEmit</code> 做的是完全一样的事情：它们向缓存中添加一个新的值。
</p>

<p>
默认情况下，当重放缓存已满时，<code>emit</code> 会暂停，直到所有订阅者开始处理缓存中最旧的值。至于 <code>tryEmit</code>，它返回  <code>false</code>，因为它不能将值添加到缓存中。如果你不自己跟踪那第四个值，这个值就会丢失。
</p>

<p>
这种行为（当重放缓存已满时）可以被改变。你也可以选择丢弃缓存中最老的值或正在被添加到缓存中的值。在这两种情况下，<code>emit</code> 都不暂停，<code>tryEmit</code> 返回 <code>true</code>。因此，在缓冲区溢出时有三种可能的行为：暂停、放弃最旧的、放弃最新的。
</p>

<div class="org-src-container">
<pre class="src src-kotlin">MutableSharedFlow(replay = 3, onBufferOverflow = BufferOverflow.DROP_OLDEST)
</pre>
</div>

<p>
<code>BufferOverflow</code> is an <i>enum</i> with three possible values: <code>SUSPEND</code>, <code>DROP_OLDEST</code>, and <code>DROP_LATEST</code>. If you don’t specify a value for <code>onBufferOverflow</code>, <code>SUSPEND</code> is the default strategy.
Buffer values
</p>
</div>
</div>
</div>
</div>
<div id="postamble" class="status">
<div class="links"><a href="#content">T</a><a href="index.html">H</a><a id="share-img">I</a><a href="20210629191000-000_index.html">0</a></div><script src="static/dom2img.min.js" type="text/javascript"></script><script src="static/x.js" type="text/javascript"></script>
</div>
</body>
</html>
