<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<!-- 2022-09-27 Tue 16:40 -->
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Programming Android with Kotlin Achieving Structured Concurrency with Coroutines</title>
<meta name="generator" content="Org Mode" />
<link rel="stylesheet" href="static/x.css" type="text/css"/><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div id="content" class="content">
<h1 class="title">Programming Android with Kotlin Achieving Structured Concurrency with Coroutines</h1>
<dl class="org-dl">
<dt>start</dt><dd><span class="timestamp-wrapper"><span class="timestamp">&lt;2022-09-15 Thu 09:26&gt;</span></span></dd>
</dl>


<p>
<code>async</code> returns a <code>Deferred</code> instance, which is a specialized <code>Job</code> with a return value.
</p>

<p>
A <code>CoroutineScope</code> is an object that plays the role of the parent in structured concurrency&#x2013;its purpose is to manage and monitor the coroutines you create inside it.
</p>

<div class="org-src-container">
<pre class="src src-kotlin">interface CoroutineScope {
  val coroutineContext: CoroutineContext
}
</pre>
</div>

<p>
In other words, a <code>CoroutineScope</code> is a container for a <code>CoroutineContext</code>.
</p>

<p>
In practice, you'll most often use a special context element to control which thread, or which thread poll, will execute your coroutine(s).
</p>

<p>
Cancellation: designed or failure
</p>

<p>
Make callback suspendable with <code>suspendCancellableCoroutine</code>:
</p>
<div class="org-src-container">
<pre class="src src-kotlin">suspend fun Call.await() = suspendCancellableCoroutine&lt;ResponseBody?&gt; { continuation -&gt;
  continuation.invokeOnCancellation {
    cancel()
  }

  enqueue(object: Callback {
    override fun onResponse(call: Call, response: Response) {
      continuation.resume(response.body())
    }

    override fun onFailure(call: Call, e: IOException) {
      continuation.resumeWithException(e)
    }
  })
}
</pre>
</div>

<p>
Catch the unhandled coroutine exceptions with <code>CoroutineExceptionHandler</code>:
</p>
<div class="org-src-container">
<pre class="src src-kotlin">fun main() = runBlocking {
  val ceh = CoroutineExceptionHandler { _, exception -&gt;
    println("Caught $exception with suppressed ${exception.suppressed.contentToString()}")
  }
  val scope = CoroutineScope(coroutineContext + ceh + Job())

  val job = scope.launch {
    try {
      throw AssertionError()
    } finally {
      withContext(NonCancellable) {
        println("Throwing exception from finally")
        throw ArithmeticException() // This exception is added to the `suppressed` list of the previous exception.
      }
    }
  }
  job.join()
}
</pre>
</div>

<p>
Stop exceptions' propagation with <code>SupervisorJob</code>:
</p>
<div class="org-src-container">
<pre class="src src-kotlin">fun main() = runBlocking {
  val ceh = CoroutineExceptionHandler { _, exception -&gt;
    println("Caught $exception with suppressed ${exception.suppressed.contentToString()}")
  }
  val supervisor = SupervisorJob()
  val scope = CoroutineScope(coroutineContext + supervisor)
  with(scope) {
    // upon could be replaced with supervisorScope
    val firstChild = launch(ceh) {
      println("First child is failing")
      throw AssertionError("First child is cancelled")
    }

    val secondChild = launch {
      firstChild.join()

      delay(10)
      println("First child is cancelled: ${firstChild.isCancelled}, but second one is still active")
    }

    // wait until the second child completes
    secondChild.join()
  }
}
</pre>
</div>

<p>
<code>withContext</code> could be replaced with <code>coroutineScope</code>
</p>

<p>
Use <code>runCatching</code> instead of <code>try/catch</code>:
</p>
<div class="org-src-container">
<pre class="src src-kotlin">scope.launch {
  val result = runCatching {
    regularFunctionWhichCanThrowException()
  }

  if (result.isSuccess) {
    // no exception was thrown
  } else {
    // exception was thrown
  }
}
</pre>
</div>

<ul class="org-ul">
<li>If the failure of a child should also cancel other children, use a regular scope. Otherwise, use a supervisor scope.</li>
<li><code>async</code> exposes exceptions, which can be caught by wrapping the <code>await</code> call in a <code>try/catch</code>. On the other hand, <code>launch</code> treats uncaught exceptions as unhandled, which can be handled using a CEH.</li>
</ul>

<p>
Unknown concepts or API:
</p>
<ul class="org-ul">
<li><code>Job.join()</code>: wait the job complete</li>
<li><code>yield</code>: give a chance to suspend unsuspendable block</li>
</ul>

<p>
next: Back Pressure
</p>
</div>
<div id="postamble" class="status">
<div class="links"><a href="#content">T</a><a href="index.html">H</a><a id="share-img">I</a><a href="20210629191000-000_index.html">0</a></div><script src="static/dom2img.min.js" type="text/javascript"></script><script src="static/x.js" type="text/javascript"></script>
</div>
</body>
</html>
